config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
  namespace :dashboard do
    root "dashboard#home"
    devise_for :admins, controllers: {sessions: "dashboard/sessions"}
    resources :categories
    resources :members
    resources :tests do
      member do
        get :publish, :draff
      end
    end
  end

  namespace :user do
    root "static_pages#home"
    devise_for :members, controllers: {registrations: "user/registrations",
      sessions: "user/sessions"}, path: ""
    get :profile, to: "members#show"
    get :published_tests, to: "tests#index"
    resources :tests do
      member do
        get :join
      end
    end
    resources :user_tests do
      resources :user_answers, only: [:create]
    end
  end
end

app/models/member.rb
class Member < User
  scope :count_tests, -> do
    joins('LEFT OUTER JOIN user_tests on user_tests.user_id = users.id')
      .select('users.*, COUNT(user_tests.test_id) as tests_count')
      .group('users.id')
  end

  ransacker :tests_count_sort do
    Arel.sql('tests_count')
  end
end

app/controllers/dashboard/categories_controller.rb
class Dashboard::CategoriesController < Dashboard::DashboardController
  before_action :find_category

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t ".success"
      redirect_to dashboard_categories_path
    else
      flash[:danger] = t ".failed"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t ".success"
      redirect_to dashboard_categories_path
    else
      flash[:danger] = t ".failed"
      render :edit
    end
  end

  def destroy
    @category.destroy
  end

  private
  def find_category
    @category = Category.find_by id: params[:id]
  end

  def category_params
    params.require(:category).permit :title
  end
end

app/controllers/dashboard/dashboard_controller.rb
class Dashboard::DashboardController < ApplicationController
  layout "dashboard"
  before_action :authenticate_dashboard_admin!

  def home
  end
end

app/controllers/dashboard/members_controller.rb
class Dashboard::MembersController < Dashboard::DashboardController
  def index
    @q = Member.ransack(params[:q])
    @members = @q.result.count_tests
  end

  def show
    @member = Member.find_by id: params[:id]
    @user_tests = @member.user_tests
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params).tap do |member|
      member.password = member.password_confirmation = Devise.friendly_token.first(8)
    end
    if @member.save
      flash[:success] = t ".success"
      MemberMailer.welcome(@member, @member.password).deliver_now
      redirect_to dashboard_members_path
    else
      flash[:danger] = t ".failed"
      render :new
    end
  end

  def destroy
    @member = Member.find_by id: params[:id]
    @member.destroy
    redirect_to dashboard_members_path
  end

  private
  def member_params
    params.require(:member).permit :name, :email, :gender
  end
end

app/controllers/dashboard/sessions_controller.rb
class Dashboard::SessionsController < ::Devise::SessionsController
  private
  def after_sign_in_path_for resource
    dashboard_root_url
  end

  def after_sign_out_path_for resource
    dashboard_root_url
  end
end

app/controllers/dashboard/tests_controller.rb
class Dashboard::TestsController < Dashboard::DashboardController
  before_action :find_test

  def index
    @tests = Test.all
  end

  def new
    @test = Test.new
  end

  def create
    @test = Test.new test_params
    if @test.save
      flash[:success] = t ".success"
      redirect_to dashboard_test_path @test
    else
      flash[:danger] = t ".failed"
      render :new
    end
  end

  def show
  end

  def edit
    redirect_to dashboard_test_path(@test) if @test.publish?
  end

  def update
    if @test.update_attributes test_params
      flash[:success] = t ".success"
      redirect_to dashboard_test_path @test
    else
      flash[:danger] = t ".failed"
      render :edit
    end
  end

  def destroy
    @test.destroy
    redirect_to dashboard_tests_path
  end

  def publish
    @test.publish!
    redirect_to dashboard_tests_path
  end

  def draff
    @test.draff! if @test.members.count == 0
    redirect_to dashboard_tests_path
  end

  private
  def find_test
    @test = Test.find_by id: params[:id]
  end

  def test_params
    params.require(:test).permit :category_id,
      questions_attributes: [:id, :content, :_destroy,
        options_attributes: [:id, :content, :correct, :_destroy]]
  end
end

app/controllers/user/members_controller.rb
class User::MembersController < User::StaticPagesController
  def show
  end
end

app/views/dashboard/members/_breadcrumb.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to t(".members"), dashboard_members_path %></li>
    <li class="breadcrumb-item"><%= link_to t(".new"), new_dashboard_member_path %></li>
  </ol>
</nav>

app/views/dashboard/members/_form.html.erb
<%= form_for [:dashboard, @member] do |f| %>
  <%= render "shared/error_messages", object: @member %>

  <div class="form-group">
    <p><%= f.label :name %></p>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <p><%= f.label :email %></p>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :gender %>
    <div class="form-check-label">
      <%= f.collection_radio_buttons :gender, Member.genders.map{|key, value| ["#{key}".capitalize, key]}, :last, :first do |b| %>
        <%= b.radio_button %>
        <%= b.label %>
      <% end %>
    </div>
  </div>

  <div class="actions text-center">
    <%= f.submit t(".create_user"), class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/dashboard/members/_member.html.erb
<tr>
  <td><%= member.name %></td>
  <td><%= member.email %></td>
  <td><%= member.tests.count %></td>
  <td><%= link_to t(".show"), dashboard_member_path(member), class: "btn btn-primary" %></td>
  <td>
    <%= link_to t(".delete"), dashboard_member_path(member), method: :delete, 
    data:{confirm: t(".confirm")}, class: "btn btn-danger" %>
  </td>
</tr>

app/views/dashboard/members/_search_form.html.erb
<%= search_form_for @q, url: dashboard_members_url, remote: true, class: "form-inline" do |f| %>
  <div class="form-group mb-2">
    <%= f.label :name_cont, t(".search_member") %>
  </div>
  <div class="form-group mx-sm-3 mb-2">
    <%= f.search_field :name_or_email_cont, class: "form-control" %>
  </div>
    <%= f.submit t(".search"), class: "btn btn-primary mb-2"  %>
  </div>
<% end %>

app/views/dashboard/members/_table_member.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col"><%= sort_link @q, :name, t(".member"), {}, {remote: true} %></th>
      <th scope="col"><%= t ".email" %></th>
      <th scope="col"><%= sort_link @q, :tests_count_sort, t(".tests"), {}, {remote: true} %></th>
      <th scope="col" colspan="2"><%= t ".action" %></th>
    </tr>
  </thead>

  <tbody>
    <%= render @members %>
  </tbody>
</table>

app/views/dashboard/members/index.html.erb
<div><%= render "breadcrumb" %></div>

<div>
  <div>
    <%= render "search_form" %>
  </div>
  <div id="index-member">
    <%= render "table_member" %>
  </div>
</div>

app/views/dashboard/members/index.js.erb
$('#index-member').html("<%= j render(partial: "table_member")%>")

app/views/dashboard/members/new.html.erb
<div><%= render "breadcrumb" %></div>
<h2><%= t ".create" %></h2>
<div class="w-50"><%= render "form" %></div>

app/views/dashboard/members/show.html.erb
<div><%= render "breadcrumb" %></div>
<h1><%= @member.name %></h1>
<p>Email: <%= @member.email %></p>
<p>Gender: <%= @member.gender %></p>
<p>Number of tests: <%= @member.tests.count%></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col"><%= t ".test" %></th>
      <th scope="col"><%= t ".category" %></th>
      <th scope="col"><%= t ".score" %></th>
      <th scope="col"><%= t ".time" %></th>
    </tr>
  </thead>

  <tbody>
    <% @user_tests.each do |u| %>
      <tr>
        <td><%= t(".test_id", id: u.test.id) %></td>
        <td><%= u.test.category.title %></td>
        <td><%= u.score %></td>
        <td><%= l(u.created_at, format: :day) %></td>
      </tr>
    <% end %>
  </tbody>
</table>