config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
  namespace :dashboard do
    root "dashboard#home"
    devise_for :admins, controllers: {sessions: "dashboard/sessions"}
    resources :categories
    resources :members
    resources :tests do
      member do
        get :publish, :draff
      end
    end
  end

  namespace :user do
    root "static_pages#home"
    devise_for :members, controllers: {registrations: "user/registrations",
      sessions: "user/sessions"}, path: ""
    get :profile, to: "members#show"
    get :published_tests, to: "tests#index"
    resources :tests do
      member do
        get :join
      end
    end
    resources :user_tests do
      resources :user_answers, only: [:create]
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests, dependent: :destroy

  validates :title, presence: true
end

app/controllers/dashboard/categories_controller.rb
class Dashboard::CategoriesController < Dashboard::DashboardController
  before_action :find_category

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t ".success"
      redirect_to dashboard_categories_path
    else
      flash[:danger] = t ".failed"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t ".success"
      redirect_to dashboard_categories_path
    else
      flash[:danger] = t ".failed"
      render :edit
    end
  end

  def destroy
    @category.destroy
  end

  private
  def find_category
    @category = Category.find_by id: params[:id]
  end

  def category_params
    params.require(:category).permit :title
  end
end

app/controllers/dashboard/dashboard_controller.rb
class Dashboard::DashboardController < ApplicationController
  layout "dashboard"
  before_action :authenticate_dashboard_admin!

  def home
  end
end

app/controllers/dashboard/members_controller.rb
class Dashboard::MembersController < Dashboard::DashboardController
  def index
    @q = Member.ransack(params[:q])
    @members = @q.result.count_tests
  end

  def show
    @member = Member.find_by id: params[:id]
    @user_tests = @member.user_tests
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params).tap do |member|
      member.password = member.password_confirmation = Devise.friendly_token.first(8)
    end
    if @member.save
      flash[:success] = t ".success"
      MemberMailer.welcome(@member, @member.password).deliver_now
      redirect_to dashboard_members_path
    else
      flash[:danger] = t ".failed"
      render :new
    end
  end

  def destroy
    @member = Member.find_by id: params[:id]
    @member.destroy
    redirect_to dashboard_members_path
  end

  private
  def member_params
    params.require(:member).permit :name, :email, :gender
  end
end

app/controllers/dashboard/sessions_controller.rb
class Dashboard::SessionsController < ::Devise::SessionsController
  private
  def after_sign_in_path_for resource
    dashboard_root_url
  end

  def after_sign_out_path_for resource
    dashboard_root_url
  end
end

app/controllers/dashboard/tests_controller.rb
class Dashboard::TestsController < Dashboard::DashboardController
  before_action :find_test

  def index
    @tests = Test.all
  end

  def new
    @test = Test.new
  end

  def create
    @test = Test.new test_params
    if @test.save
      flash[:success] = t ".success"
      redirect_to dashboard_test_path @test
    else
      flash[:danger] = t ".failed"
      render :new
    end
  end

  def show
  end

  def edit
    redirect_to dashboard_test_path(@test) if @test.publish?
  end

  def update
    if @test.update_attributes test_params
      flash[:success] = t ".success"
      redirect_to dashboard_test_path @test
    else
      flash[:danger] = t ".failed"
      render :edit
    end
  end

  def destroy
    @test.destroy
    redirect_to dashboard_tests_path
  end

  def publish
    @test.publish!
    redirect_to dashboard_tests_path
  end

  def draff
    @test.draff! if @test.members.count == 0
    redirect_to dashboard_tests_path
  end

  private
  def find_test
    @test = Test.find_by id: params[:id]
  end

  def test_params
    params.require(:test).permit :category_id,
      questions_attributes: [:id, :content, :_destroy,
        options_attributes: [:id, :content, :correct, :_destroy]]
  end
end

app/views/dashboard/categories/_breadcrumb.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to t(".categories"), dashboard_categories_path %></li>
    <li class="breadcrumb-item"><%= link_to t(".new"), new_dashboard_category_path %></li>
  </ol>
</nav>

app/views/dashboard/categories/_category.html.erb
<tr id="category-<%= category.id %>">
  <td><%= category.title %></td>
  <td><%= category.tests.count %></td>
  <td><%= link_to t(".show"), dashboard_category_path(category), class: "btn btn-primary" %></td>
  <td><%= link_to t(".edit"), edit_dashboard_category_path(category), class: "btn btn-success" %></td>
  <td>
    <%= link_to t(".delete"), dashboard_category_path(category), remote: true, method: :delete, 
    data:{confirm: t(".confirm")}, class: "btn btn-danger" %>
  </td>
</tr>

app/views/dashboard/categories/_form.html.erb
<%= form_for [:dashboard, @category] do |f| %>
  <%= render "shared/error_messages", object: @category %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: t(".insert"), class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Create category", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/dashboard/categories/destroy.js.erb
$('#category-<%= @category.id %>').html('');

app/views/dashboard/categories/edit.html.erb
<div><%= render "breadcrumb" %></div>

<h1><%= t ".edit" %></h1>
  <div class="col-md-8">
    <%= render "form" %>
  </div>

app/views/dashboard/categories/index.html.erb
<div><%= render "breadcrumb" %></div>

<div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col"><%= t ".category" %></th>
        <th scope="col"><%= t ".tests" %></th>
        <th scope="col" colspan="3"><%= t ".actions" %></th>
      </tr>
    </thead>

    <tbody>
      <%= render @categories %>
    </tbody>
  </table>
</div>

app/views/dashboard/categories/new.html.erb
<div><%= render "breadcrumb" %></div>

<h2><%= t ".new" %></h2>
  <div class="col-md-8">
    <%= render "form" %>
  </div>

app/views/dashboard/categories/show.html.erb
<div><%= render "breadcrumb" %></div>

<h2><%= @category.title %></h2>
<% @tests = @category.tests %>
<%= render partial: "dashboard/tests/table_test" %>