config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
  namespace :dashboard do
    root "dashboard#home"
    devise_for :admins, controllers: {sessions: "dashboard/sessions"}
    resources :categories
    resources :members
    resources :tests do
      member do
        get :publish, :draff
      end
    end
  end

  namespace :user do
    root "static_pages#home"
    devise_for :members, controllers: {registrations: "user/registrations",
      sessions: "user/sessions"}, path: ""
    get :profile, to: "members#show"
    get :published_tests, to: "tests#index"
    resources :tests do
      member do
        get :join
      end
    end
    resources :user_tests do
      resources :user_answers, only: [:create]
    end
  end
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests, dependent: :destroy

  validates :title, presence: true
end

app/models/member.rb
class Member < User
  scope :count_tests, -> do
    joins('LEFT OUTER JOIN user_tests on user_tests.user_id = users.id')
      .select('users.*, COUNT(user_tests.test_id) as tests_count')
      .group('users.id')
  end

  ransacker :tests_count_sort do
    Arel.sql('tests_count')
  end
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question
  has_many :user_answers

  validates :content, presence: true

  enum correct: {wrong: 0, right: 1}
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :options, inverse_of: :question, dependent: :destroy
  has_many :user_answers

  accepts_nested_attributes_for :options, reject_if: :all_blank,
    allow_destroy: true

  validates :content, presence: true
  validate :correct_option, :option_numbers

  def correct_option
    if options.select{|option| option.right? && !option.marked_for_destruction?}.count != 1
      errors.add(:options, "- There must be only 1 correct option")
    end
  end

  def option_numbers
    if options.select{|option| !option.marked_for_destruction?}.count <= 1
      errors.add(:options, "must be greater than 1")
    end
  end
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  has_many :user_tests, dependent: :destroy
  has_many :members, through: :user_tests
  has_many :questions, inverse_of: :test, dependent: :destroy

  enum status: {draff: 0, publish: 1}

  accepts_nested_attributes_for :questions, reject_if: :all_blank,
    allow_destroy: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_tests
  has_many :tests, through: :user_tests
  enum gender: {female: 0, male: 1}
end

app/models/user_answer.rb
class UserAnswer < ApplicationRecord
  belongs_to :user_test
  belongs_to :question
  belongs_to :option

  scope :right, ->{joins(:option).merge(Option.right)}
end

app/models/user_test.rb
class UserTest < ApplicationRecord
  belongs_to :member, class_name: "User", foreign_key: "user_id"
  belongs_to :test
  has_many :user_answers

  enum complete: {uncompleted: 0, completed: 1}

  validates :user_id, uniqueness: {scope: :test_id}

  scope :highest_score, -> {order score: :desc}

  after_update :update_score

  def update_score
    result = user_answers.right.size.to_f / test.questions.size * 10
    update_column(:score, result)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  devise_group :user, contains: [:admin, :member]
end

app/controllers/dashboard/members_controller.rb
class Dashboard::MembersController < Dashboard::DashboardController
  def index
    @q = Member.ransack(params[:q])
    @members = @q.result.count_tests
  end

  def show
    @member = Member.find_by id: params[:id]
    @user_tests = @member.user_tests
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params).tap do |member|
      member.password = member.password_confirmation = Devise.friendly_token.first(8)
    end
    if @member.save
      flash[:success] = t ".success"
      MemberMailer.welcome(@member, @member.password).deliver_now
      redirect_to dashboard_members_path
    else
      flash[:danger] = t ".failed"
      render :new
    end
  end

  def destroy
    @member = Member.find_by id: params[:id]
    @member.destroy
    redirect_to dashboard_members_path
  end

  private
  def member_params
    params.require(:member).permit :name, :email, :gender
  end
end

app/controllers/dashboard/tests_controller.rb
class Dashboard::TestsController < Dashboard::DashboardController
  before_action :find_test

  def index
    @tests = Test.all
  end

  def new
    @test = Test.new
  end

  def create
    @test = Test.new test_params
    if @test.save
      flash[:success] = t ".success"
      redirect_to dashboard_test_path @test
    else
      flash[:danger] = t ".failed"
      render :new
    end
  end

  def show
  end

  def edit
    redirect_to dashboard_test_path(@test) if @test.publish?
  end

  def update
    if @test.update_attributes test_params
      flash[:success] = t ".success"
      redirect_to dashboard_test_path @test
    else
      flash[:danger] = t ".failed"
      render :edit
    end
  end

  def destroy
    @test.destroy
    redirect_to dashboard_tests_path
  end

  def publish
    @test.publish!
    redirect_to dashboard_tests_path
  end

  def draff
    @test.draff! if @test.members.count == 0
    redirect_to dashboard_tests_path
  end

  private
  def find_test
    @test = Test.find_by id: params[:id]
  end

  def test_params
    params.require(:test).permit :category_id,
      questions_attributes: [:id, :content, :_destroy,
        options_attributes: [:id, :content, :correct, :_destroy]]
  end
end

app/controllers/user/members_controller.rb
class User::MembersController < User::StaticPagesController
  def show
  end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < ::Devise::SessionsController
  private
  def after_sign_in_path_for resource
    user_root_url
  end

  def after_sign_out_path_for resource
    user_root_url
  end
end

app/controllers/user/static_pages_controller.rb
class User::StaticPagesController < ApplicationController
  layout "user"
  before_action :authenticate_user_member!

  def home
  end
end

app/controllers/user/tests_controller.rb
class User::TestsController < User::StaticPagesController
  def index
    @category = Category.all
    if params[:category_id].present?
      @tests = Test.where(category_id: params[:category_id]).publish
    else
      @tests = Test.publish
    end
  end

  def join
    @test = Test.find_by id: params[:id]
    @user_test = @test.user_tests.find_or_create_by(user_id: current_user_member.id)
    @user_test.update_column(:expired_at, @user_test.created_at + 30*60)
    CompleteTestWorker.perform_at(30.minutes.from_now, @user_test.id)
    redirect_to edit_user_user_test_path @user_test
  end
end

app/controllers/user/user_answers_controller.rb
class User::UserAnswersController < User::StaticPagesController
  def create
    question = Option.find(params[:user_answer][:option_id]).question
    user_answer = UserTest.find(params[:user_test_id]).user_answers
      .find_or_initialize_by(question_id: question.id)
    user_answer.update!(user_answer_params)

    respond_to do |format|
      format.json { head :ok }
    end
  end

  private
  def user_answer_params
    params.require(:user_answer).permit(:option_id)
  end
end

app/controllers/user/user_tests_controller.rb
class User::UserTestsController < User::StaticPagesController
  before_action :find_user_test

  def index
    @current_tests = current_user_member.user_tests.uncompleted
    @user_tests = current_user_member.user_tests.completed.highest_score
  end

  def show
    @questions = @user_test.test.questions
  end

  def edit
    if @user_test.completed?
      redirect_to user_user_test_path(@user_test)
    else
      @questions = @user_test.test.questions
    end
  end

  def update
    @user_test.completed!
    redirect_to user_user_test_path(@user_test)
  end

  private
  def find_user_test
    @user_test = UserTest.find_by id: params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_dashboard_footer.html.erb
<footer class="app-footer">
  <div>
    <a href="https://coreui.io">Ravio</a>
    <span>&copy; <%= Time.current.year %> creativeLabs.</span>
  </div>
  <div class="ml-auto">
    <span>Powered by</span>
    <a href="https://coreui.io">Ravio</a>
  </div>
</footer>

app/views/layouts/_dashboard_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to t(".dashboard"), dashboard_root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link active" href="<%= user_root_path %>">User Page</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown">
          <%= current_dashboard_admin.name %>
        </a>
        <div class="dropdown-menu">
          <%= link_to t(".log_out"), destroy_dashboard_admin_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_dashboard_sidebar.html.erb
<nav class="sidebar-nav">
  <ul class="nav">
    <li class="nav-title"><%= t ".model" %></li>
    <li class="nav-item">
      <%= link_to t(".members"), dashboard_members_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to t(".categories"), dashboard_categories_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to t(".tests"), dashboard_tests_path, class: "nav-link" %>
    </li>
  </ul>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
  <div class="container">
    <%= link_to "App Test", user_root_path, class:"navbar-brand" %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav text-uppercase ml-auto">
        <li class="nav-item">
          <%= link_to "All tests", user_published_tests_path, class: "nav-link" %> 
        </li>
        <li class="nav-item">
          <%= link_to "Your tests", user_user_tests_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "profile", user_profile_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_member_session_path, method: :delete, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_user_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
  <div class="container">
    <%= link_to "App Test", user_root_path, class:"navbar-brand" %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav text-uppercase ml-auto">
        <li class="nav-item">
          <%= link_to "All tests", user_published_tests_path, class: "nav-link" %> 
        </li>
        <li class="nav-item">
          <%= link_to "Your tests", user_user_tests_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "profile", user_profile_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_member_session_path, method: :delete, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppTest1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppTest1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/@coreui/coreui/dist/css/coreui.min.css">
  </head>

  <body class="app sidebar-show aside-menu-show">
    <%= render "layouts/dashboard_header" %>
    <div class="app-body">
      <div class="sidebar">
        <%= render "layouts/dashboard_sidebar" %>
      </div>
      <main class="main p-3">
        <%= yield %>
      </main>
      <%# <aside class="aside-menu">
        <!-- Aside menu content here -->
      </aside> %>
    </div>
    <%= render "layouts/dashboard_footer" %>

    <script src="https://unpkg.com/@coreui/coreui/dist/js/coreui.min.js"></script>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppTest1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
  </head>

  <body id="user">
    <%= render "layouts/user_header" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>